version: '3.8'

services:
  gateway-db:
    image: postgres:15
    container_name: gateway-db
    restart: always
    environment:
      POSTGRES_DB: gateway-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - gateway_db_data:/var/lib/postgresql/data
    networks:
      - gateway-network

volumes:
  gateway_db_data:

networks:
  gateway-network:
    driver: bridge
