version: '3.8'

services:

  # ZOOKEEPER Server
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # KAFKA Server
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

  # Eureka Discovery Server
  eureka-server:
    image: openjdk:17-jdk
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - micro-network

  # Gateway
  gateway:
    image: openjdk:17-jdk
    container_name: gateway
    build:
      context: ./gateway-service/gateway-service
      dockerfile: Dockerfile
    ports:
      - "8732:8732"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - write-service
      - read-service
      - auth-service
    networks:
      - micro-network

  # Write Service
  write-service:
    image: openjdk:17-jdk
    container_name: write-service
    build:
      context: ./write-service/write-service
      dockerfile: Dockerfile
    ports:
      - "7878:7878"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - micro-network

  # Read Service
  read-service:
    image: openjdk:17-jdk
    container_name: read-service
    build:
      context: ./read-service/read-service
      dockerfile: Dockerfile
    ports:
      - "7979:7979"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - micro-network

    # Auth Service
  auth-service:
    image: openjdk:17-jdk
    container_name: auth-service
    build:
      context: ./auth-service/auth-service
      dockerfile: Dockerfile
    ports:
      - "7676:7676"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - micro-network  

  # PostgreSQL (optionnel)
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: gateway-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - micro-network

# Volumes
volumes:
  pgdata:

# Networks
networks:
  micro-network:
    driver: bridge





 