server:
  port: 7878
 
spring:
  # Application name
  application:
    name: write-service
  
  #Configure Files
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  
  # Configure DB
  datasource:
    url: jdbc:postgresql://localhost:5432/gateway-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver  
  
  # JPA let flyway manage schema
  jpa:
    hibernate:
      ddl-auto: none    
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration    
    
 
  
  #Kafka
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
#        spring.json.value.default.type: com.ansarbachir.application.dto.*
        

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
                        
    admin:
      auto-create: true  
          
#Discovery service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
 
 
#KAFKA PROPERTIES
kafka:
   group-id: myGroup
   topic:
     post:
       create: create-post-topic
       update: update-post-topic
       partitions: 1
       replicas: 1

logging:
  level:
    org.springframework.kafka: DEBUG
    org.springframework.kafka.listener: DEBUG
    org.apache.kafka: INFO   

app:
  file:
    storage-location: C:\Users\ansar\Desktop\uploads   