server:
  port: 7979
 

spring:
  application:
    name: read-service
    
  # Configure DB
  datasource:
    url: jdbc:postgresql://localhost:5432/gateway-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: none    
    properties:
      hibernate:
        format_sql: true
        show_sql: true
   
   

#Discovery service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
       
app:
  file:
    storage-location: C:\Users\ansar\Desktop\uploads      