# Run the gateway server on port 8732
server:
  port: 8732
 
spring:
  # Application name
  application:
    name: gateway-server

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: write-service
              uri: lb://write-service
              predicates:
                - Path=/api/v1/write/**
              filters:
                - StripPrefix=3
                
            # READ SERVICE
            - id: read-service
              uri: lb://read-service
              predicates:
                - Path=/api/v1/read/**
              filters:
                - StripPrefix=3    
            
            # AUTH SERVICE
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - StripPrefix=3    

          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
  
#Discovery service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: YW5zYXJiYWNoaXJfc29jaWFsc1BsYXRmb3JtX0JhY2tlbmRfQVBJXzExXzIwMjU=
  issuer: ansarbachir
  type: accessToken
 

  
