# Run the gateway server on port 8732
server:
  port: 8732
 
spring:
  # Application name
  application:
    name: gateway-server
  
  # Configure DB
  datasource:
    url: jdbc:postgresql://localhost:5432/gateway-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  # JPA let flyway manage schema
  jpa:
    hibernate:
      ddl-auto: none    
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration  

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # First MS for all writing operations   
        - id: command-service
          uri: lb://command-service
          predicates:
            - Path=/api/command/**
          filters:
            - StripPrefix=1
        
        # Second MS for all reading operations
        - id: query-service
          uri: lb://query-service
          predicates:
            - Path=/api/query/**
          filters:
            - StripPrefix=1

#Discovery service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    
 
  
